my_dbt_project:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: gen-lang-client-0635762262
      dataset: analytics
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: /secrets/gcp-key.json
