version: 2

sources:
  - name: postgres_bronze
    database: gen-lang-client-0635762262
    schema: bronze
    tables:
      - name: transactions
      - name: accounts
      - name: devices
      - name: merchants
